version: "3.9"

services:
  node:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data

    entrypoint: 
      - node
      - /app/ganache-core.docker.cli.js
      - --db=/ganache_data
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'live genius aerobic observe remain husband allow main disorder protect oak powder'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug
# ENTRYPOINT ["node", "./build/cli.node.js"]
# ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]
