# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Smart Contracts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./monedero-hardhat
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Environment
        uses: actions/setup-node@v4
      - name: Test
        run: |
          npm i
          npx hardhat coverage
          ls -laR coverage
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
            coverage-summary-path: ./monedero-hardhat/coverage/coverage-final.json
            output-folder: badges-hardhat
        